//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingControls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBulgarian {
            get {
                return ((bool)(this["isBulgarian"]));
            }
            set {
                this["isBulgarian"] = value;
=======
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int currentWSindex {
            get {
                return ((int)(this["currentWSindex"]));
            }
            set {
                this["currentWSindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chinese")]
        public string currentWS {
            get {
                return ((string)(this["currentWS"]));
            }
            set {
                this["currentWS"] = value;
>>>>>>> 23e017fecc78ea1afe501226aaacae23f442804f
            }
        }
    }
}
