//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingControls {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class SettingsHolder : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsHolder defaultInstance = ((SettingsHolder)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsHolder())));
        
        public static SettingsHolder Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentWSindex {
            get {
                return ((int)(this["CurrentWSindex"]));
            }
            set {
                this["CurrentWSindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chinese")]
        public string CurrentWS {
            get {
                return ((string)(this["CurrentWS"]));
            }
            set {
                this["CurrentWS"] = value;
            }
        }
    }
}
